apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p7fja5ozu-python
  janus-idp.io/tekton: p7fja5ozu-python
  backstage.io/kubernetes-id: p7fja5ozu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p7fja5ozu-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
